services:
  frontend:
    init: true
    build:
      context: ./
      target: setup
      dockerfile: ./frontend/Dockerfile
    volumes:
      - webfiles:/frontend
    command: npm run dev -- --host
    ports:
      - 3000:3000

volumes:
  webfiles:
